/** Entry-level IT job categories used by the job form and the Smart Daily Target system. */
export const JOB_CATEGORIES: string[] = [
  "IT Support",
  "Desktop Support",
  "Service Desk",
  "Help Desk",
  "Technical Support",
  "IT Analyst",
  "Application Support",
  "Network Support",
  "Network Engineer",
  "System Administrator",
  "SOC Analyst",
  "Cyber Security Analyst",
  "Information Security Analyst",
  "Security Operations",
  "Cloud Support",
  "Cloud Engineer",
  "Software Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "QA Tester",
  "DevOps Engineer",
  "Data Analyst",
  "Business Analyst",
  "IT Operations",
];
